cc_library(

    name = "speech_to_text",

    srcs = ["speech_to_text.cc"],

    visibility = ["//visibility:public"],

    deps = [

    "//mediapipe/framework:calculator_framework",

    ],

    alwayslink = 1,

)